version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: AlumnoNFL
      MYSQL_DATABASE: rls
      MYSQL_USER: auditoriasrsl
      MYSQL_PASSWORD: yHTT5LFuuUnYiW8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - webnet

  php:
    image: php:8.3.6-fpm
    container_name: php-fpm
    volumes:
      - ./codigo:/usr/share/nginx/html
    networks:
      - webnet

  web:
    image: allunell/rsl-dockerizado:v1
    restart: always
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./codigo:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./codigo/style:/usr/share/nginx/style  # Se añadió este volumen para la carpeta de CSS
    networks:
      - webnet
    depends_on:
      - php

volumes:
  mysql_data:

networks:
  webnet:
    driver: bridge
